name: Update CMC Data Daily

on:
  schedule:
    - cron: '*/10 * * * *'  
  workflow_dispatch:    

permissions:
  contents: write

jobs:
  
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run CMC data update script
      env:
        CMC_PRO_API_KEY: ${{ secrets.CMC_PRO_API_KEY }}
      run: |
        python src/update_cmc_data.py
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data.csv
        git diff --quiet && git diff --staged --quiet || git commit -m "Update crypto data [skip ci]"
        git push